### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by SidFeng** [yuanyan/react-native-web-example#6]
react-web start

let isProd = NODE_ENV === 'production';
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/sid/Documents/react/react-native-web-example/node_modules/react-web/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at _server (/Users/sid/Documents/react/react-native-web-example/node_modules/react-web/local-cli/server.js:27:23)
    at /Users/sid/Documents/react/react-native-web-example/node_modules/react-web/local-cli/server.js:22:5

I do not know what I have done something wrong

**Comment by SidFeng** [comment]
brew upgrade node

It is working now
