### ISSUE TITLE
react-web start error

### ISSUE THREAD

**Issue by qussers** [yuanyan/react-native-web-example#9]
command not found 怎么办？

**Comment by qussers** [comment]
ERROR in Path must be a string. Received undefined

**Comment by qussers** [comment]
nvm v6降到v4 上面的问题没了 新问题出现了。。polling-xhr.js:250 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LSK0Sn6 404 (Not Found) 救命sos

**Comment by yefan813** [comment]
" ERROR in Path must be a string. Received undefined " I have same problem

**Comment by kingflight** [comment]
"ERROR in Path must be a string. Received undefined" 
webpack: bundle is now VALID.

版本：
react-web-cli: 0.0.4
react-web: 0.2.5

我也遇到了，麻烦看看。

**Comment by robinkam** [comment]
ERROR in Path must be a string. Received undefined
我也遇到这个问题，唉……

**Comment by thiswhy** [comment]
真不知道还需要更改哪里才能跑起来，现在的版本到了0.46了，已经不能用这个0.17版本的做了。也是挺急的，有没有人解决一下？

**Comment by jacqui126** [comment]
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (E:\test-project\react-native-web-example\node_modules\natives\index.js:143:24)
    at Object.req [as require] (E:\test-project\react-native-web-example\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (E:\test-project\react-native-web-example\node_modules\webpack\node_modules\graceful-fs\fs.js:1:37)

node : V10.17.0
webpack : 4.41.2

**Comment by Jacqui-Guo** [comment]
> " ERROR in Path must be a string. Received undefined " I have same problem

node版本降到5.x就行了
